### PR TITLE
Lemmas without glosses 733 and minimalpairs to CSV 743

### PR DESCRIPTION
**Pull request by susanodd**
This branch has the following:

- allows deletion of lemma's that have no glosses, along with their related translation objects. This functionality is offered on the Lemma List page. There is a confirm dialog. The deletion only applies to lemma's without glosses that are in the queried results.

- adjusts the order during export of minimal pairs to CSV to account for large files. The minimal pairs are computed before generation of the file is started. Previously, the file was created and then written row by row as the minimal pairs were computed. While the computation time is still slow, 15 minutes for NGT, it does not timeout/crash any more, at least on my local server.

-  includes a bugfix with the links in the results scroll bar

- adds magic to the python virtual environment requirements

### CODE REVIEW

**Comment by susanodd** [comment]
@vanlummelhuizen @Woseseltops any idea when you'll have time to review?

**Comment by Woseseltops** [comment]
Sorry for the wait @susanodd ! Will try today or else tomorrow.

**Comment by Woseseltops** [comment]
My remarks:

* I got a bit confused by the fact that these seem to be unrelated issues. Or is there some relation, @susanodd ? If unrelated, not the end of the world of course, but I would say it makes more sense to only group issues that are about related additions/fixes, and create smaller pull requests for the rest. Besides clarity for the reviewer, an advantage would be that one pull request (and thus feature) can already be deployed while the other is revised.

* For #733 the code seems fine (I actually learned about annotating datasets, thanks!), but I have done a few small extra functional suggestions in the issue.

* For #735 I think you forgot to include the main commit ;) . I have asked a question out of curiosity there.

* For #743, some more UI/UX is required, but that shouldn't stop us from putting this live already.

**Comment by susanodd** [comment]
Bullet 2 (#733) has been completed! Good idea to add the count to be deleted!

Bullet 1 is mainly because I work on a number of issues and wait until the previous merge request has been completed before creating a new branch for the new issues. (I don't like to work on an older version because I get used to working with all the changes on my branch. It all gets tested more that way, too.)
It would be easier if I could keep spanning new branches from the branch I'm still working on.

Bullet 3 (#735) is already on the server. That's how @ocrasborn got the error message about Magic, because I'd forgot to put that in the requirements file on the previous branch where this issue was fixed. The requirements file is included here.

**Comment by susanodd** [comment]
@Woseseltops regarding creating branches for issues...
Since requesting review on this branch, I've completed two issues involving colours in pull-down menus (#726 and #727), morpheme tags (#748), and the H in revision history (#741).
The H doesn't have anything to do with the others. And the morpheme tags issue was encountered while working on the colour pull-downs. The Morpheme View has also been modified a bit qua formatting.
My changes are all still on this branch, because I'm waiting for it to be merged before creating a new branch for these issues which are all ready to go.

**Comment by Woseseltops** [comment]
Deployed!

**Pull request merged**
