### PR TITLE
Annotated sentences panel added #1178

### PR DESCRIPTION
**Pull request by Jetske**
This is ready to test on signbank-dev

### CODE REVIEW

**Comment by Jetske** [comment]
@susanodd the settings for temporary files is now added to default.py so that can be deleted from the server specific settings

**Review by Woseseltops — COMMENTED** [review]
Great work @Jetske. I wasn't aware that there was an `Eaf` object in the `pympi` library, cool. 

Two things to consider:

* I'm a bit confused by `object_type=a`... is there a reason to not just make it more descriptive (`object_type=annotated_sentence`?)

* In the Javascript part, I notice you build some html from strings. This is done in more places within Signbank, but I believe a cleaner way to do something like

```javascript
tableHtml += '<thead><tr><th style="width:200px">Gloss</th><th style="width:200px">Representative</th><th style="width:200px">starttime</th><th style="width:200px">endtime</th></tr></thead>';
```

would be something like

```javascript

    // Create a jQuery object for the table
    var table = $('<table>');

    // Create a jQuery object for the table header section
    var thead = $('<thead>');

    // Create a table row for the header
    var headerRow = $('<tr>');

    // Create and append table header cells to the header row
    var glossHeader = $('<th>').text('Gloss').css('width', '200px');
    var repHeader = $('<th>').text('Representative').css('width', '200px');
    var startTimeHeader = $('<th>').text('starttime').css('width', '200px');
    var endTimeHeader = $('<th>').text('endtime').css('width', '200px');

    // Append each header cell to the header row
    headerRow.append(glossHeader);
    headerRow.append(repHeader);
    headerRow.append(startTimeHeader);
    headerRow.append(endTimeHeader);

    // Append the header row to the table header section
    thead.append(headerRow);

    // Append the table header section to the table
    table.append(thead);
```

It takes way more space though, so I'm not 100% sure. I see this table is built using data from a POST request; another approach could be to built the table server side using the Django template language.

**Comment by Jetske** [comment]
@Woseseltops Agreed :) 

The object-type first had only 2 options and then was extended. There is no good reason not to write those names out in full. 

And I added a template to create the annotations table. To be honest I find it less readable, but it is probably more conform the Django rules to have it separated like that.

**Comment by Woseseltops** [comment]
> To be honest I find it less readable, but it is probably more conform the Django rules to have it separated like that.

For completeness, as long as it's a conscious decision, I'm totally okay with not conforming to Django rules; a comment along the lines of 'adding html as string for readability purposes' would also have been okay. However, now that I see the template approach you just added, I personally do prefer it, so thanks :).

**Comment by susanodd** [comment]
The html needs to be constructed as @Jetske did with jquery, otherwise the nesting structure is incorrect in some browsers. Safari can't parse things with non-structured html.

**Pull request merged**
