### PR TITLE
Export Empty CSV Template

### PR DESCRIPTION
**Pull request by susanodd**

### CODE REVIEW

**Comment by susanodd** [comment]
@Woseseltops this is deployed on signbank-susan

**Review by Woseseltops — APPROVED** [review]
Code looks fine. @uklomp , are you willing to do a functional review on https://signbank-susan.cls.ru.nl/signs/import_csv_create/ ?

**Comment by uklomp** [comment]
I will do this on Monday! Thanks for the links.

**Comment by uklomp** [comment]
OK, it was Tuesday late afternoon. It's not working for me, see the issue #1131 please.

**Comment by susanodd** [comment]
I'll go ahead and merge this since the template is okay.

**Pull request merged**
