### PR TITLE
Various issues from the odd branch

### PR DESCRIPTION
**Pull request by susanodd**
This branch adds the following new features:

- search feature for lemmas
- scroll bar for search results on lemmas on lemma update page
- export media hyperlinks on dataset management page
- compounds in gloss relations view
- colors in pull-down queries on field choices in settings->preview gloss colors search

Other supporting issues:

- keyboard shortcuts during gloss editing in field choice pull-down lists
- admin for field choices now prevents creation of duplicates
- admin uses the setting SHOW_FIELD_CHOICE_COLORS to hide the new field_color if necessary
- sorting of compound parts in display of gloss
- sorting of handshapes in handshape list view
- lemma translations required in lemma edit view on save

Please check whether the setting SHOW_FIELD_CHOICE_COLORS needs refinement to work with ASL.

### CODE REVIEW

**Comment by susanodd** [comment]
I pushed the fix for search by Morpheme Type (get_queryset of GlossListView).

**Comment by susanodd** [comment]
I undid the commented out testSettings test_Settings (https://github.com/Signbank/Global-signbank/pull/731#commitcomment-46961711)

The settings test fails because of the SWITCH_TO_MYSQL setting

**Comment by Woseseltops** [comment]
This branch consists of the following issues:

#492
#660 
#689
#693
#699
#705
#708
#714
#716
#720
#721
#722
#727
#729

My goal is go over them today and possibly tomorrow. I will try to understand the issues, and the solutions in the code, and will provide any suggestions if they pop into my head.

**Comment by Woseseltops** [comment]
Okay did not get anywhere near what I wanted to achieve today. I only did: #492, #660, #689, #699, #705.

Busy with: #708

Postponed because of size: #693

**Comment by Woseseltops** [comment]
Almost there. Done: #708, #714, #716, #720, #721, #722

Todo: #693 #727

**Comment by Woseseltops** [comment]
Update: everything is reviewed. We can merge once @susanodd processes my last things (or decided not to).

**Comment by susanodd** [comment]
I made all the revisions of @Woseseltops.

With the exception of: the comment about (not using) a signbank jeditable javascript file.
I can work on this, but it will take a while.

The main issue in this new code is that in order to use colours, the browser select statements have been changed to lists.
Albeit select2 does this too, override the browser by making copies and hiding the original.
The extra issue with our code is the search key shortcuts for navigating. It is complicated by the ajax calls if updating
The use of select2 in the "gloss search" is read-only, whereas the Gloss Edit view is not.

I will investigate this, but this is a back burner endeavour.

**Comment by susanodd** [comment]
@vanlummelhuizen ?

**Comment by vanlummelhuizen** [comment]
> @vanlummelhuizen ?

@susanodd I am not sure what exactly you want me to respond to. Could you enlighten me?

**Comment by susanodd** [comment]
Is it okay to merge? Or are you still reviewing?

**Pull request merged**
