### PR TITLE
Immediate dataset access procedure #849 and #850

### PR DESCRIPTION
**Pull request by Jetske**
Needs to be reviewed! 

I _think_ it works alright, tested it by checking whether access was granted and by looking at the emails that are sent when trying to access new datasets as regular user. But I did not test the actual send_mail command. 

From how I understand it, requesting access to private (not "accessible by others") datasets should not be possible because the buttons for that are hidden in the menu 'datasets > view available datasets'. However, if this does happen somehow, a request email is supposed to be sent to the owner. 

And lastly, I couldn't figure out the difference between dataset owners and dataset managers and assumed the words are used interchangeably. Correct me if I'm wrong.

### CODE REVIEW

**Comment by susanodd** [comment]
There exist test users that @ocrasborn created that belong to different groups. (I'm not sure if he knows the passwords anymore.)

In the code you'll see places where print statements (commented out) exist near the send_mail. 
Also it's possible to create a test for this and grant the user specific permissions or assign them to specific groups.
There are some tests for datasets that do this. (With the print statements instead of the send_mail.)

**Comment by Woseseltops** [comment]
> From how I understand it, requesting access to private (not "accessible by others") datasets should not be possible because the buttons for that are hidden in the menu 'datasets > view available datasets'. However, if this does happen somehow, a request email is supposed to be sent to the owner.

It think this outside the scope of the current issue, but indeed, when a new user X is created, X can only see public datasets. Not 100% sure, but it might be possible that an admin user adds X to another user group with more permission, and then X might be able to see and request access to all datasets.

**Review by Woseseltops — COMMENTED** [review]
Good work. I like that you:
* Nicely divide the code into 'paragraphs', each with their own explanation comment
* Thought of changing the actual email prose :)

Minor complaints:
* I see there a few commented debug print statements. They are nicely explained, so it's clear why they are there... but perhaps it would be cleaner as a setting? So you can all turn them on and off in one go.
* Still an (active) print statement in `adminviews.py` ;)

**Comment by Jetske** [comment]
Thanks for checking @Woseseltops !
I just added the debug option as setting to default.py, not sure if it is cleaner but it is definitely faster to activate this way

**Pull request merged**
