### PR TITLE
Simple dark option

### PR DESCRIPTION
**Pull request by susanodd**
Nearly all code revisions needed to implement this make all the constant background settings that are white have become inherit.

The modals have the dark-mode class added otherwise they become transparent if they're just inherit.
The select2 selections now have an extra identity function to keep the black color of the pull-downs,
This is also done for dynamic pull-down choices.
Use is made of opacity (as it is also done in Bootstrap) in order to display the pull-down of the form on top of the "dark mode" elements behind it. This works well on some pull-downs but makes them less visible in light mode.

### CODE REVIEW

**Comment by Woseseltops** [comment]
Instead of putting draft in the title, I used the Github features to mark this as draft :)

**Comment by susanodd** [comment]
This is on signbank-susan now.

I realise it's not ready for review, but it needs feedback and implementation suggestions from others. :)

(How best to modify with minimal effort so it's functional.)

**Comment by susanodd** [comment]
Okay, there's a newer version online. (The images below are from signbank-susan.)

Due to kind of arbitrary nesting of html and use of tags, some of the things are really difficult to turn dark.

I got the Gloss Edit to work. I added an extra class to the clickable panel headings to get them dark. (It's still kind of ugly.)

The "Lemma" values are invisible in dark mode, and only turn red if you click on Edit.
(I can't figure out where the formatting is coming from on some things.)

The select lists show up, but it needs more adjustment to make them not white.
(This is because we use colours in the lists here.)

gloss-edit-dark-mode-1

gloss-edit-dark-mode-2

gloss-edit-dark-mode-3

**Comment by susanodd** [comment]
I suspect GitHub is using different shades of black.
I tried using some predefined html colours like darkgrey, but that is kind of useless.
Some of the bootstrap things make use of opacity. That kind of backfires.

**Comment by susanodd** [comment]
dark-mode-twilight-style

**Comment by susanodd** [comment]
@Woseseltops do you know anything about the "origins" of Signbank, specifically the Bootstrap stuff.

I am having trouble figuring out how a "table" element is getting a "transparent" background. In none of our code do we set any tables to transparent.

In the browser, this "transparent" is being inherited from the bootstrap css files in the Signbank archive.
There is a "`{% load bootstrap3 %}`" on all the templates which is doing this.

(So all the "inherit" settings eventually end up with that stupid transparent setting if they inherit enough levels back.
I'm having trouble figuring out how to override this.)

**Comment by susanodd** [comment]
The alpha channel bootstrap colours cause problems in dark mode because it's opposite. For some reason they end up looking like a blue haze around stuff. (The box shadows of Bootstrap that make stuff float.)

**Comment by susanodd** [comment]
A few more templates have been modified to support dark mode.
Some problems with the top "affix" part of the pages becomes more obvious in dark mode.
The "menu bar" plus "scroll bar" plus "navigation tabs" plus "login / logout / profile" plus "interface language selection" plus "Query" and "Edit" "Copy" buttons (visible in the header in some templates) all overlap each other.
The affix things work by way of a z-index. The height of all of these things is computed dynamically. But this is sometimes messed up in some templates, depending on when the code was written.

**Review by Woseseltops — CHANGES_REQUESTED** [review]
Cool, love it. My only feedback is that I think the Javascript is not DRY enough. For example, where you now do (just picked a random excerpt):

```javascript

  $(".navbar").each(function () {
        if ($(this).hasClass("navbar-light")) {
            $(this).removeClass("navbar-light");
            $(this).addClass("navbar-dark");
        } else if ($(this).hasClass("navbar-dark")) {
            $(this).removeClass("navbar-dark");
            $(this).addClass("navbar-light");
        }
  });
  $(".navbar-nav").each(function () {
        if ($(this).hasClass("navbar-nav-light")) {
            $(this).removeClass("navbar-nav-light");
            $(this).addClass("navbar-nav-dark");
        } else if ($(this).hasClass("navbar-nav-dark")) {
            $(this).removeClass("navbar-nav-dark");
            $(this).addClass("navbar-nav-light");
        }
  });
  $(".navbar-form").each(function () {
        if ($(this).hasClass("navbar-form-light")) {
            $(this).removeClass("navbar-form-light");
            $(this).addClass("navbar-form-dark");
        } else if ($(this).hasClass("navbar-form-dark")) {
            $(this).removeClass("navbar-form-dark");
            $(this).addClass("navbar-form-light");
        }
  });
  $(".navbar-text").each(function () {
        if ($(this).hasClass("navbar-text-light")) {
            $(this).removeClass("navbar-text-light");
            $(this).addClass("navbar-text-dark");
        } else if ($(this).hasClass("navbar-text-dark")) {
            $(this).removeClass("navbar-text-dark");
            $(this).addClass("navbar-text-light");
        }
  });

```

you could probably do

```javascript

function toggleClasses(selector, lightClass, darkClass) {
    $(selector).each(function () {
        $(this).toggleClass(lightClass).toggleClass(darkClass);
    });
}

toggleClasses(".navbar", "navbar-light", "navbar-dark");
toggleClasses(".navbar-nav", "navbar-nav-light", "navbar-nav-dark");
toggleClasses(".navbar-form", "navbar-form-light", "navbar-form-dark");
toggleClasses(".navbar-text", "navbar-text-light", "navbar-text-dark");
```

or even something like

```javascript

function toggleClasses(selector) {
    $(selector).each(function () {
        $(this).toggleClass(".navbar-"+selector+"-light").toggleClass(".navbar-"+selector+"-dark");
    });
}

toggleClasses("");
toggleClasses("nav");
toggleClasses("form");
toggleClasses("text");

```

---

Also, for completeness, I wanted to mention I think some of the bright colors should be a bit darker in dark mode, but let's postpone that to a later issue :)

Now
image


Suggestion:
image

**Comment by susanodd** [comment]
Very nice toggle suggestion!

As you can guess, it got a bit out of hand because I underestimated how many of the toggle classes there would need to be.
There are so many because of all the nesting and things needing to inherit and override other things.
It kept getting longer and longer with the toggle classes.

Okay, we can figure out the colours later. I think the font isn't very good either. It looks really chunky in white.

**Pull request merged**
