### PR TITLE
Issue #869: Refined feedback add new gloss page.

### PR DESCRIPTION
**Pull request by susanodd**
Improvements to the `update.py` function `add_gloss` as requested by @Woseseltops in the review of #867.

See the screenshots in the Issue for more details.

### CODE REVIEW

**Comment by susanodd** [comment]
See new improvement screenshots in #869

**Review by Woseseltops — COMMENTED** [review]
This is beautiful code wise, thanks! 

One thing I noticed design wise is that you introduce a grey button here, while I think in Signbank we use mostly blue buttons (or white for less important). There probably are cases where accidentally a grey button made it to production, but since I'm reviewing this code right now, I thought I should mention it :)

**Comment by susanodd** [comment]
Hmmm. I actually can't tell if the button is grey or white on my screen. Should it be white?
I looked up the code of the CSV export button on the Gloss List View.
It's actually an `input` field of class `btn btn-default`
On the add-gloss template, the Copy annotations button is actually a `button` of type `button` (without any class styling)
On the w3schools bootstrap_buttons page, I honestly can't see any color on the Basic and Default, except when you hover, the Basic is darker grey on hovering. (Maybe Firefox messes with the display?)

**Comment by susanodd** [comment]
Hmmm. In looking for examples, the Dataset Manager page has both kinds of buttons. (Slightly differently looking.)

**Comment by susanodd** [comment]
blue-copy-fields-button

**Comment by susanodd** [comment]
I completed the requested fixes, so this can be merged.

**Pull request merged**
