### PR TITLE
#1330: Report constraint error as alert to user, not as message

### PR DESCRIPTION
**Pull request by susanodd**
Extended feedback message to include id of conflicting gloss.

This branch is not on any server.

### CODE REVIEW

**Comment by susanodd** [comment]
@vanlummelhuizen I see in the update_gloss method of update.py there are some already existing "returns" that are inconsistent.
Most are HttpResponse but delete gloss has HttpResponseRedirect. It's not possible to return to Gloss Edit if the gloss has been deleted.

**Review by Woseseltops — APPROVED** [review]
Looks good!

I do prefer f-strings though :) . Instead of 

```python
 msg = "The annotation idgloss translation text '%s' is not unique within dataset '%s' for gloss '%s'. Gloss %s also has this text." % (self.text, dataset.acronym, self.gloss.id, gloss_with_same_text.id)
```

you get

```python
msg = f"The annotation idgloss translation text '{self.text}' is not unique within dataset '{dataset.acronym}' for gloss '{self.gloss.id}'. Gloss {gloss_with_same_text.id} also has this text."
```

**Comment by susanodd** [comment]
> Looks good!
> 
> I do prefer f-strings though :) . Instead of
> 
> ```python
>  msg = "The annotation idgloss translation text '%s' is not unique within dataset '%s' for gloss '%s'. Gloss %s also has this text." % (self.text, dataset.acronym, self.gloss.id, gloss_with_same_text.id)
> ```
> 
> you get
> 
> ```python
> msg = f"The annotation idgloss translation text '{self.text}' is not unique within dataset '{dataset.acronym}' for gloss '{self.gloss.id}'. Gloss {gloss_with_same_text.id} also has this text."
> ```

This is to do with already existing translations of the first sentence. I added a second sentence.
The text as a whole is poorly written because it's two sentence now.
But then all the translations will need to be done with some un-handy Python patterns in the translations.
(Those are difficult to translate because the syntax isn't the same in all languages.)

**Comment by susanodd** [comment]
I modifed it as you show.

We were supposed to make it be a link to the other gloss.
But I think that is not wise because the control flow should be to "close" the alert (using browser button in "alert") not to jump out of it to a completely different page.

**Pull request merged**
