### PR TITLE
Improvements for editing annotated sentences issue #1234

### PR DESCRIPTION
**Pull request by Jetske**

### CODE REVIEW

**Comment by susanodd** [comment]
@Jetske I put this branch on signbank-dev to make sure the migration works okay.

I'm not able to test this myself because of the eaf files.

Can you check whether it works as expected?
Then I'll merge it with master and then merge it into the api_interface branch so all the branches are using the migration.

**Comment by Jetske** [comment]
@susanodd this should be ready to merge, can you do that and deploy? It has one migration.

**Comment by susanodd** [comment]
> @susanodd this should be ready to merge, can you do that and deploy? It has one migration.

Okay!

**Comment by Jetske** [comment]
Sorry, I notice that I need to change something still.

**Pull request merged**
