### PR TITLE
Related Signs View: Fixed issues with pattern variants.

### PR DESCRIPTION
**Pull request by susanodd**
I fixed some issues with pattern variants showing up for some glosses.
I also removed the hard coded languages in the template.

### CODE REVIEW

**Comment by susanodd** [comment]
There were some hard-coded languages in the Relations View.
While repairing that with an additional setting, I noticed the glitch in the original code was also used in Gloss Detail View, so I repaired that as well.

**Comment by susanodd** [comment]
There was a glitch appearing with variants.
It's possible to store a variant relation explicitly.
It's also possible to let them be found using patterns.
The (new and improved) Gloss Frequency View also shows variants.
In testing that code, I looked for glosses with variants.
It became evident that the handling of variants was inconsistent.
I revised the code to be more robust. Modifications were made to the the "pattern" search.
The old code was exposing BEER-A to be a variant of BIER-A.
(Via the English Annotation, instead of only looking at the same language.)

**Comment by Woseseltops** [comment]
I am a bit confused here. This pull request refers to an issue which is about simply adding another hardcoded relation type, but that commit is not part of this pull request... instead, I believe this is about things for which there are no issues:
* A small fix for pattern variants
* Moving things related to hardcoded translation languages to the view (instead of the template)

 @susanodd , is this correct?

About the last thing, you replaced all of the translated field choices with `get_FIELDCHOICE_display`, like `get_handedness_display`, which seems super elegant to me... but how does it work? Where can I find the code that takes as input a field choice and an interface language, and then outputs the correct human value?

Furthermore, reviewing the code, I noticed you are using `x` as variable name a few times in for loops... I guess these are a good candidate for some quick readability improvement?

**Comment by susanodd** [comment]
The issue that adds a new relation type needs this issue to be committed because of the template Relations View.
I completely rewrote that code for that template. But it's not live yet.
The issue that adds a new relation type needs the newest template.
The "live" signbank template Relations View has hard coded languages in it.

**Comment by susanodd** [comment]
The fix isn't that small. It repairs a bug.

**Comment by susanodd** [comment]
This branch is ready to merge with the master.

**Comment by susanodd** [comment]
@Woseseltops Branch relations_between_signs (for #764) is waiting on this branch to be merged.
This branch makes changes to the GlossRelationsDetailView template and removes the hard coded languages.

**Comment by susanodd** [comment]
Brought up to date with most recent master.

**Comment by Woseseltops** [comment]
Hey @susanodd , did another review of this code today. Overall I'm happy, but as nearly always I have some stuff to complain about :)

 My feedback:

```python
        if len(queries) > 1:
            query = queries.pop()
            for q in queries:
                query |= q
        else:
            try:
                query = queries[0]
            except:
                query = []
```

This part strikes me as confusing... It tries to transform something inside `queries` to `query`, but I don't understand what the end result is or why and why you use `pop` the first time, but not afterwards. I think we need at least (1) a comment explanation, (2) more descriptive variable names and (3) something to follow `except`. In other words, there must be a reason why you can't do it simply like this

```python

merged_single_query = []
for q in queries:
    merged_single_query |= queries
```

and the reader should be able understand right away.

I think the code directly below that can be cleaner:

```python
        other_relations_of_sign = self.other_relations()
        other_relation_objects = [x.target.id for x in other_relations_of_sign]

        if queries:
            pattern_variants = Gloss.objects.filter(query).exclude(id__in=other_relation_objects).distinct()
        else:
            pattern_variants = [ self ]
```

```python
        if queries:
           #Run the query, but exclude all glosses that have a relation to this gloss
            related_gloss_ids = [relation.target.id for relation in self.other_relations()]
            pattern_variants = Gloss.objects.filter(query).exclude(id__in=related_gloss_ids).distinct()
        else:
            pattern_variants = [ self ]
```

Other than that it's go my thumbs up :)

**Comment by susanodd** [comment]
That's a good question about the queries syntax. (First comments above.) I will rewrite it. It may have been written as so because of types.
In other issues, I discovered during testing (a different issue) that I needed to explicitly create an empty query result rather than an empty list. I suspect it only happens during run-time.
In some of the templates, it's only checked whether something has a value, the variable or function result is non-empty.
That's probably how type errors would arise because the template is only checking whether the thing is non-empty and ignores it if not. At the very least, there should be three cases, >1, 1, 0. So it's very weird that I put the exception in there.
Probably it was generating a type error on None or [] instead of empty query.

For the second statement, I know I am paranoid about things not being evaluated right away.
That's the main reason I put things in separate assignments, to force (strict) evaluation rather than ending up with a giant database expression. I was under the impression that statements like Gloss.objects..... creates a database query.

**Comment by susanodd** [comment]
It does not seem to work with the alternative deconstruction.
The Q elements are different than normal list elements.
the "|" operator needs a non-empty Q element to start.

**Comment by susanodd** [comment]
It looks slightly different but more or less as you suggested, @Woseseltops !

**Comment by Woseseltops** [comment]
Great, thanks! Could you please:
* Also add 1 sentence comment explaining why 

> That's the main reason I put things in separate assignments, to force (strict) evaluation rather than ending up with a giant database expression. I was under the impression that statements like Gloss.objects..... creates a database query.

You might very well be right! Unless you are 100% sure something won't work, my preference would be to try the pretty solution first, and only make it uglier when it turns out there's a bug or performance problem.

**Comment by susanodd** [comment]
Okay, I see what's a bit weird. The merged query expression used to operate on the list variable "queries" which includes patterns to search for for variants. The list constructed now contains at least three patterns. Originally, this only contained one pattern so the subsequent code originally tested whether it was empty or not.
The pop is used to remove one of the Q patterns from this list. Then the rest are iterated over with the for loop.
Except after popping, a Q element has been removed. So the subsequent "if queries" test is looking at the queries expression with that popped element removed. Although this doesn't matter for the code, it's only concerned with whether there is a Q expression to use as a filter. Yes, there is actually a type problem in this code depending on which branch is followed!
Good idea to include a comment. The code probably needs a different constructor for the empty case.

**Pull request merged**
