### PR TITLE
fix: Add a decorator to put API user in request #1278

### PR DESCRIPTION
**Pull request by vanlummelhuizen**
I tried to create a solution that is elegant and reusable.

### CODE REVIEW

**Comment by vanlummelhuizen** [comment]
A remark: as it is now implemented there are no errors that could be passed to the client like what happens in https://github.com/Signbank/Global-signbank/blob/fb97037616378827661b13c5530d282184b4a13c/signbank/api_interface.py#L100

I think I can implement it so that errors could be passed. I will work on that next week.

**Review by Woseseltops — APPROVED** [review]
Fancy walrus operator

**Comment by vanlummelhuizen** [comment]
> Fancy walrus operator

Nice that you noticed. Unfortunately (?) I removed it in my latest changes. 

I think this is ready to merge now, if approved of course.

**Comment by vanlummelhuizen** [comment]
> I think this is ready to merge now, if approved of course.

Hmm, I keep finding things to improve in the API. Perhaps keep this PR open until I have finished checking all API endpoints.

**Comment by susanodd** [comment]
Looks good to me! Much cleaner.

**Comment by vanlummelhuizen** [comment]
@Woseseltops @susanodd @Jetske 

I have gone over all endpoint as documented in https://github.com/Signbank/Global-signbank/wiki/Signbank-API and added the `put_api_user_in_request` decorator and changed some code where applicable.

**Note:** The following function seems to need some work. For instance, the `errors` variable is a string that is never send back to the user. https://github.com/Signbank/Global-signbank/blob/fb97037616378827661b13c5530d282184b4a13c/signbank/api_interface.py#L468-L505

**Comment by vanlummelhuizen** [comment]
Ready to merge afaic

**Review by Jetske — APPROVED** [review]

**Comment by susanodd** [comment]
> @Woseseltops @susanodd @Jetske
> 
> I have gone over all endpoint as documented in https://github.com/Signbank/Global-signbank/wiki/Signbank-API and added the `put_api_user_in_request` decorator and changed some code where applicable.
> 
> **Note:** The following function seems to need some work. For instance, the `errors` variable is a string that is never send back to the user.
> 
> https://github.com/Signbank/Global-signbank/blob/fb97037616378827661b13c5530d282184b4a13c/signbank/api_interface.py#L468-L505

Hmmm. I see that. It looks like it might be testing things that are already tested at a previous step.
Sometimes, to make type check etc it is needed to check for things that don't happen.
(Not related, but an example of, when we know something is unique, but use "first" anyway and ignore the case when there could have been multiple objects. Then test if first is empty. There is lots of code that does this for the dataset languages.)

But could it happen I guess if somebody knew about the url and didn't follow the previous steps.
But it looks like I just ignored these, but tested anyway. (Remove code? Or give a Http warning and crash out?)

**Comment by susanodd** [comment]
I actually don't know how to "approve" on GitHub.

**Review by Woseseltops — APPROVED** [review]
Improves maintainability

**Review by susanodd — APPROVED** [review]

**Comment by susanodd** [comment]
> Ready to merge afaic

Okay, it's probably time.

**Pull request merged**
