### PR TITLE
Only add senses to ecv descriptions, not phonology #1325

### PR DESCRIPTION
**Pull request by Jetske**
@susanodd @Woseseltops @vanlummelhuizen question: MPI want to only have senses in the ECV gloss descriptions, not phonology or other information. Would this be ok to put that in the default settings? Does anyone else use these ECV files?

### CODE REVIEW

**Comment by Woseseltops** [comment]
When say MPI, you mean ELAN, right? I think ELAN is the only user of the ECVs indeed, but I'm not 100% sure. The fastest way to find out is to just change it and listen for complaints :).

Also, do note that we override this setting in `server_specific/global_sb_new_aj.py`!

**Review by Woseseltops — APPROVED** [review]

**Comment by Jetske** [comment]
Yes, I mean ELAN :)
Okay so then I made the changes in server_specific/global_sb_new_aj.py instead of default.py

**Comment by ocrasborn** [comment]
Hi @Jetske @Woseseltops ! :-)

> When say MPI, you mean ELAN, right? I think ELAN is the only user of the ECVs indeed, but I'm not 100% sure. The fastest way to find out is to just change it and listen for complaints :). 

Perhaps 'MPI' means the users of the Corpus NGT there, I'm thinking of PhD candidate Jenni Sander in particular, who works on NGT child data and may refer to Signbank in their own annotations as well. 

Anyway, I just thought I'd add some background here should people wonder in the future how the ECV came to be what it is now: before the Signbank Lexicon Service feature in ELAN existed, annotators adding glosses to their timelines had a hard time differentiating glosses that are very much alike (think of HOUSE-A and HOUSE-B, for instance). We added an extract of the Signbank phonology to the description field at the time, so that annotators would know which gloss refers to which phonological form. (Truth be told, in practice most deaf and hearing annotators found this info hard to read and use, but researchers found it very handy.) Now that the semantic description of signs has taken better shape in the form of ordered senses, AND now that the Lexicon Service in ELAN can pop up a video of the sign form when selecting or inspecting a gloss, it makes total sense to remove the phonology from the description field. I would check with @uklomp at UvA though whether that doesn't interfere with any workflow they have.

**Comment by susanodd** [comment]
@Woseseltops do you want me to merge and deploy this?

**Comment by Jetske** [comment]
@susanodd Yes!

**Pull request merged**
