### PR TITLE
Fixes to obsolete file names and wrong version numbering for backups

### PR DESCRIPTION
**Pull request by susanodd**
Fixes to bak bak old style file names. Fixes a bug in the API that all backups are given version number 1.

- Some of the code is still using `(version * ".bak") `extensions. That has been changed to the new format `.bakNNNN`

- The logging has been repaired to only put a deleted video in the history, not all the reverted videos (those are still on the file system)
- The renumbering of older backups has been updated so they get new version numbers
- The retrieval of GlossVideo objects explicitly excludes subclass objects (only the prime videos are versioned)

The branch includes a minimum amount of code to achieve the goal: use the new format for file names.

Old file names can be repaired elsewhere (pull requests in other branches)

### CODE REVIEW

**Comment by susanodd** [comment]
@vanlummelhuizen I am in the process of renaming the bak bak files using a command I made. There have been some glitches, but most of them are fixed.

Here is an example of something weird:

`
rename_backup_videos move  /var/www/writable/glossvideo/ISL/עו/עולה-49544.bak.bak /var/www/writable/glossvideo/ISL/עו/עולה-49544.mp4.bak21688`

Why is the original file not in a folder? Why is the filename a number instead of text? It looks like it messed up the "left to right" versus "right to left".

**Comment by vanlummelhuizen** [comment]
> rename_backup_videos move /var/www/writable/glossvideo/ISL/עו/עולה-49544.bak.bak /var/www/writable/glossvideo/ISL/עו/עולה-49544.mp4.bak21688

This file is in folder `/var/www/writable/glossvideo/ISL/עו` but because of the right-to-left order of the Hebrew text, that part including the slash is displayed in reverse order from what we are used to.

The same goes for the other file you mention:

```sh
root@signbank-new:/var/www/writable/glossvideo# ll /var/www/writable/glossvideo/ZEI/جو/
total 1054
drwxrwxr-x  2 root wwwsignbank      5 Nov 13 09:24 ./
drwxrwxr-x 75 root wwwsignbank     75 Mar 30  2023 ../
-rwxrwxr-x  1 root wwwsignbank 844854 Mar 30  2023 جوجه-37107.mp4*
-rwxrwxr-x  1 root wwwsignbank 112113 Mar 30  2023 جوجه-37107.mp4.bak11859*
-rwxrwxr-x  1 root wwwsignbank  77055 Mar 30  2023 جوجه-37107_small.mp4*
```

**Comment by susanodd** [comment]
I found a bug. If I delete a video in Gloss Edit, the backup file that has the `.mp4.bakNNNN` extension is being put in writeable, not in glossvideo.
Something is wrong with reversion.
I did not change the reversion code yet, it's still using the (original) code this branch is meant to fix.

**Comment by susanodd** [comment]
@vanlummelhuizen I tried repeating some of the commands locally, to try to obtain an error. For the SHEEP video for ZEI, it gives this error:

<h1>TypeError
       at /video/upload/</h1>
  <pre class="exception_value">not all arguments converted during string formatting</pre>
  
Request Method: | POST
-- | --
http://localhost:8000/video/upload/
4.2.15
TypeError
not all arguments converted during string formatting
/home/susan/signbank/src/NGT-signbank/signbank/dictionary/models.py, line 2419, in add_video
signbank.video.views.addvideo

**Comment by susanodd** [comment]
It looks like the version number isn't being set properly when a new reversion is done.
It also does not  check whether the file actually exists. (Locally, it keeps making objects with the new `mp4.bakNNN `extensions but there are no files for them.)

**Comment by vanlummelhuizen** [comment]
@susanodd It is very hard for me to judge whether your code will work correctly. I suggest you create a test environment that is (almost) the same as the live server. Perhaps the test server could serve that purpose. 

Also, make a plan of how to apply the changes and run the commands that are necessary to make things correct. Please show us that plan. (Perhaps that also helps me to see what is involved.)

Finally, when doing all this on the live server, I think it is wise to backup all media files explicitly.

**Comment by susanodd** [comment]
> @susanodd It is very hard for me to judge whether your code will work correctly. I suggest you create a test environment that is (almost) the same as the live server. Perhaps the test server could serve that purpose.
> 
> Also, make a plan of how to apply the changes and run the commands that are necessary to make things correct. Please show us that plan. (Perhaps that also helps me to see what is involved.)
> 
> Finally, when doing all this on the live server, I think it is wise to backup all media files explicitly.

This is a bit annoying. I did not write the original reversion code. I'm trying to fix very old code that I did not write.

I have tested it on signbank-test for new videos that get uploaded and then deleted.

The command `remove_unused` can be used and just choose N to not do anything. This can be safely run on the production server to examine what is there.

@Jetske and I discussed this off-line. What we don't know is whether it is necessary to keep all of these backup files?

@uklomp said they don't need backups like this. Their users keep their own videos and can upload them again, if needed.

**Comment by uklomp** [comment]
Yes, I did say that, but that might only be true for the NGT data.

**Comment by vanlummelhuizen** [comment]
@susanodd My point here is that we need to be careful, because, other than for NGT, people may not have backups themselves.

**Comment by susanodd** [comment]
> @susanodd My point here is that we need to be careful, because, other than for NGT, people may not have backups themselves.

I tried to summarize the important aspects of this issue.

I did not know what the code was actually doing, so time was spent figuring out what it was doing.

It looks like when a gloss is deleted, the video of the gloss remains on the file system, but there is no GlossVideo object pointing to it anymore (because the gloss does not exist). This ends up stored in DeletedGlossOrMedia, where you can see a filename and the former gloss ID saved there.

I suppose it would be possible to restore a video that way. But we have zero implementation of this. Moreover, the phonology etc. was not stored. That's why we introduced Archival.

I was totally unaware that there were videos of deleted glosses on the file system. But they are unaccessible.
It's also nearly impossible to write general code that accounts for switching between left to right and right to left.
(The Python paths are not necessarily correct for this.)

I agree we need to be careful. But it is also difficult to tell how much of the "backup and deleted media" is outdated.

I prefer to have Admin pages that summarize what is there. For the DeletedGlossOrMedia, it would be possible to add a column to check for the existence of the file on the file system.

The way the bakNNN reversion is implemented, it's actually just modifying version numbers (it used to be adding more bak's to it.) It modified the filenames stored in the objects regardless or not of whether there is actually a file. (I saw it was doing this locally.)

So there are lots of weird things going on with the code.

I focussed on making it work for new uploads and deletes.

But it is also dangerous if it's about really old glosses. They are hard to find in the Admin because the newest is first (depending which table you search, they are ordered differently). It searches on the annotation, but the glosses are stored by the lemma. So it's possible you do not see an older object because there are thousands of objects. This is mainly relevant for the test dataset, since we've made some really weird lemma names and they don't look at all like the annotations.

Probably some additional information is needed in the Admin.
It's most useful for checking if a file exists for a GlossVideo object.
The same would be helpful for the DeletedGlossOrMedia.
The Gloss Video History as misleading. It's also showing unsuccessful attempts to upload videos. So repeated attempts to upload show up. (The objects are created but the file may not have been saved.)

**Comment by susanodd** [comment]
@vanlummelhuizen this code basically doesn't do anything different. The command mentioned is optional. It already has existed for a very long time. I only changed the print log to display the entire path, not just the filename.

The code that needs to be "approved" (or not) is the change to the file name creation that does `(version * ".bak")`
That code needs to disappear to stop doing that. It's been putting extra "bak's" on the end of the bakNNNN. That is the bug this is fixing.

**Comment by susanodd** [comment]
@vanlummelhuizen 

Preface to bug: I browse the videos in the ADMIN to make sure objects are not being created without any video files.
There is one for AANDOEN-46565 (you can search on it, but it only shows up in the lemma since it's been archived.
The GlossVideo object does not have a video file.

Continued: So I was looking in the folder `glossvideo/NGT/AA` to see if there is a file for it with some other name.

What caught my eye in that folder is the folllowing (see details below)

It seems the API is making these. (The API uses the same add_video method) The version of video upload API that uses a zip file overwrites an already existing video. 

<details>


```
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 15:15 AARDPLAAT-47555.mp4.bak101101
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 15:15 AARDPLAAT-47555.mp4.bak101104
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 18:17 AARDPLAAT-47555.mp4.bak109771
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 18:17 AARDPLAAT-47555.mp4.bak109774
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 21:18 AARDPLAAT-47555.mp4.bak118441
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 21:18 AARDPLAAT-47555.mp4.bak118444
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 00:20 AARDPLAAT-47555.mp4.bak127114
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 00:20 AARDPLAAT-47555.mp4.bak127117
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 03:21 AARDPLAAT-47555.mp4.bak135784
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 03:21 AARDPLAAT-47555.mp4.bak135787
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 06:15 AARDPLAAT-47555.mp4.bak144458
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 06:16 AARDPLAAT-47555.mp4.bak144461
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 10:14 AARDPLAAT-47555.mp4.bak153773
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 10:14 AARDPLAAT-47555.mp4.bak153776
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 14:14 AARDPLAAT-47555.mp4.bak163133
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 14:14 AARDPLAAT-47555.mp4.bak163136
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 18:14 AARDPLAAT-47555.mp4.bak172496
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 18:14 AARDPLAAT-47555.mp4.bak172499
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 24 22:14 AARDPLAAT-47555.mp4.bak181856
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 24 22:14 AARDPLAAT-47555.mp4.bak181859
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 25 02:14 AARDPLAAT-47555.mp4.bak191222
-rw-r--r-- 1 ubuntu www-data    1342762 Sep 23 09:43 AARDPLAAT-47555.mp4.bak20010
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 22 14:39 AARDPLAAT-47555.mp4.bak31774
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 22 14:39 AARDPLAAT-47555.mp4.bak31777
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 22 18:15 AARDPLAAT-47555.mp4.bak40441
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 22 18:16 AARDPLAAT-47555.mp4.bak40444
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 22 21:15 AARDPLAAT-47555.mp4.bak49111
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 22 21:16 AARDPLAAT-47555.mp4.bak49114
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 00:16 AARDPLAAT-47555.mp4.bak57781
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 00:16 AARDPLAAT-47555.mp4.bak57784
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 03:16 AARDPLAAT-47555.mp4.bak66451
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 03:16 AARDPLAAT-47555.mp4.bak66454
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 06:13 AARDPLAAT-47555.mp4.bak75121
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 06:14 AARDPLAAT-47555.mp4.bak75124
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 09:15 AARDPLAAT-47555.mp4.bak83770
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 09:15 AARDPLAAT-47555.mp4.bak83773
-rw-r--r-- 1 ubuntu wwwsignbank 1581584 Nov 23 12:15 AARDPLAAT-47555.mp4.bak92434
-rw-r--r-- 1 ubuntu wwwsignbank 1342762 Nov 23 12:15 AARDPLAAT-47555.mp4.bak92437
```

**Comment by susanodd** [comment]
This works correctly on signbank-test. The bak videos are numbered correctly.

**Comment by susanodd** [comment]
UPDATE @Woseseltops 

On signbank-test you can


- Use the Swagger API to upload videos
- To confirm that the version numbers are being incremented (the bug on master/production sets them to 1)
- Use `Manage Datasets -> Manage Video Storage` to inspect the paths of the gloss video objects

**Comment by susanodd** [comment]
> @susanodd It is very hard for me to judge whether your code will work correctly. I suggest you create a test environment that is (almost) the same as the live server. Perhaps the test server could serve that purpose.
> 
> Also, make a plan of how to apply the changes and run the commands that are necessary to make things correct. Please show us that plan. (Perhaps that also helps me to see what is involved.)
> 
> Finally, when doing all this on the live server, I think it is wise to backup all media files explicitly.

This comment is actually not about what this branch is doing..

It is fixing the code for NEW backup videos. Some code on master uses `(version * ".bak")`

I included @Jetske command here to be able to inspect what files are in the file system but do not have any objects.

**Review by Woseseltops — APPROVED** [review]
* Nothing to complain about code wise.
* Functionally, I tested as @susanodd describes and can confirm that using the API to upload multiple video files results in backups like this

```python
0: glossvideo/NGT/WE/WEBCAM-2211.mp4, 1: glossvideo/NGT/WE/WEBCAM-2211.mp4.bak24466, 2: glossvideo/NGT/WE/WEBCAM-2211.mp4.bak10152
```

**Pull request merged**
