### PR TITLE
Crowded view

### PR DESCRIPTION
**Pull request by susanodd**
Changes for #1259 

This is on `signbank-dev`

Revised base layout header and menu bar so menu bar wraps and stays inside same element

This keeps the header bar elements from floating over the scroll bar and query button area.

To solve, only the datasets viewable by the user are shown in the header.
There are too many datasets to fit in the header on small screens. This causes things in the header to float around and interfere with other things.
The RU logo image path has been moved / put inside the html code instead of inside CSS where it was.
This to allow its dimension to be available and to put it on the right.
The background page color was removed from the "hands" logo SVG code. This was causing it to have dimension.

The scroll bar is now 100 % visible on an 11 inch Macbook Air. No need to keep reloading the page.

This branch will need to be tested  by colleages with different browsers and computer screens.

### CODE REVIEW

**Comment by susanodd** [comment]
Reviewers are asked to help fix things that don't work on their browser......

**Comment by susanodd** [comment]
The very last commit that makes `edit_text` become `edit_area` is not yet on `signbank-dev`. It's been tested on Safari with a small screen and fixes the remaining edit layout problems with width in gloss view.

**Comment by Woseseltops** [comment]
Looks good @susanodd . The only thing I don't understand is what is the function of the `gloss skeleton` in 2-3 sentences?

**Comment by susanodd** [comment]
> Looks good @susanodd . The only thing I don't understand: what is the function of the `gloss skeleton`, in 2-3 sentences?

No function. It was an early working file. To gather the overall nesting structure of the html elements.  I think it would help if the structure blocks could be made clear. There are references to specific element ids that give the structure. But in some places, these were no longer the blocks on the page.

(I will delete this. But the problem behind still remains wrt code maintenance. Header, Menus, Scrollbar, Affix Header, Navigation Panels, Left Column, Right Column, etc. None of this pops out.)

**Pull request merged**
