### PR TITLE
API update lemma and annotation fields

### PR DESCRIPTION
**Pull request by susanodd**
This is live on signbank-dev !!!!

This checks for database conflicts before allowing to update.

- already used annotations or lemmas for the dataset and language
- shared lemmas cannot be updated

Also for the API update, modification of strings stored in Gloss Revision History for Senses.

The history has some quirks because the senses updates are done as a whole.
This has been done using a loop over the "before" senses and in turn the "after" senses, using the `__str__` method of the Sense class and a join using '`|||`' to separate. These are both modular, but the strings are stored in the history when saved.

The update to the lemma and annotation fields includes mappings between three different "labels" all available in interface languages.

- the display column human-readable header (used in templates)
- the API retrieval JSON header (used in '`package`', it avoids excessive parentheses)
- the internal label with underscores used in form fields

The two first two are multilingual and mapped by model translations. This allows the API user to provide field choice values for e.g., Dutch phonology. For the language fields for lemma and annotations, (2) has been implemented due to the different syntax for these in the API package that already existed.

### CODE REVIEW

**Comment by susanodd** [comment]
Some of the code is a bit hard to read and some print statements are still there.

Because this is a high priority issue (#1243) the coding was written with priority on asap instead of style.

**Comment by Woseseltops** [comment]
I'll do the code review part... but about the functionality: as this was requested by @rem0g , would it make sense if he tests on signkbank-dev.cls.ru.nl whether this works as he needs?

**Comment by rem0g** [comment]
Yes i can test that at signbank dev

**Review by Woseseltops — COMMENTED** [review]
Looks good to me. My only complaint is that it's unclear to me what some of the functions do, like `internal_language_fields`, `revision_history_senses`, `check_value_dict_update_gloss_language_fields` or `gloss_update_fields_check` and `gloss_update_typecheck`. 

Giving some sort of hint of the output already makes a function more descriptive, for example `collect_revision_history_for_senses` or `detect_type_related_problems_for_gloss_update`. Not sure if my proposals actually cover the content, it's just an example of what I feel would be easier to maintain.

**Comment by susanodd** [comment]
Okay, thanks! I will take that approach. (I implemented it as if bailing out water, so I just kept adding code. It's confusing for me to read, too.)

**Pull request merged**
