### PR TITLE
Issue #735: Other media files Gloss/Morpheme view/upload.

### PR DESCRIPTION
**Pull request by susanodd**
Modifications to Other Media section of Gloss Detail View.
Checks for existence of file and greys out download if something is wrong.
Upload quotes the input filename if necessary and uses that instead of the original filename on the user's computer.
Upload checks that the file type is okay.

### CODE REVIEW

**Comment by susanodd** [comment]
Here's a screenshot showing the Other Media.
The greyed out one is not on my local server. It's also disabled.
If you hover, you can see the href of both of the media files, but clicking on the greyed out one does nothing.

other-media-greyed-out-disabled

**Comment by susanodd** [comment]
Here's an example of trying to upload a "csv" file where the extension has been altered (by me) to ".png".
This generates an error.

select-fake-png-file

error-message-fake-media

**Comment by susanodd** [comment]
I searched the database and only found a test pdf file that had been uploaded.
I was concerned that there were so many python files and text files. (These are not on my machine.)
They were at the time uploaded to static. The original paths are in the OtherMedia objects.
That's why everything with bad paths gets greyed out now.

I added the video/* and image/* filter so that the browser limits the choice.
Is it possible to leave this until users request otherwise?

**Comment by susanodd** [comment]
I guess they're all OSError.

**Comment by susanodd** [comment]
I had problems with the os calls sometimes because of special characters in filenames.
I have a couple of sample files on my computer with Farsi characters in the filenames.
So conceivably, every single "os" call could throw an exception?
That's why the code takes apart the original filename to check the format.
The R->L filenames of the original file were causing problems.

**Comment by susanodd** [comment]
Probably some of these need to be in the media folder for tests. Although it's deliberately making things that are supposed to throw exceptions.

**Comment by susanodd** [comment]
I tried out adding an accept for application/pdf files.
It works okay to upload them.

I created a pdf by saving a CSV file as PDF inside of LibreOffice (on Ubuntu).
I don't have any software to create PDF files other than that.

The source file opens okay, so nothing is wrong with the actual file. And if I save the uploaded file it is also okay.
But Firefox doesn't start up a viewer for it, it has to be downloaded.

**Comment by susanodd** [comment]
I completed all of @Woseseltops requests.

**Review by Woseseltops — APPROVED** [review]
Awesome @susanodd , thank you for processing my whining ;) . Hereby my seal of approval.

@vanlummelhuizen , you agree we don't need two approvals every time?

**Comment by vanlummelhuizen** [comment]
> you agree we don't need two approvals every time?

@Woseseltops  I agree.

**Comment by susanodd** [comment]
@vanlummelhuizen can you put this live?

**Comment by vanlummelhuizen** [comment]
@susanodd I will. If I cannot find the time today, I will do it first thing tomorrow.

**Comment by vanlummelhuizen** [comment]
@susanodd Done!

**Pull request merged**
