### PR TITLE
API for create and delete sentences, URL field added #1203

### PR DESCRIPTION
**Pull request by Jetske**
This includes 
- Addition of URL field for annotated video (migration!)
- A correction for the gloss create API in swagger
- New endpoints for get (through glosses), create, update, and delete for annotated sentences + added to swagger

### CODE REVIEW

**Comment by susanodd** [comment]
> @susanodd do you have time to review/+merge this? Note the migration :)

I think @Woseseltops ought to look at this as well as the perspective videos pull request, since both have migrations of the video models.
Esp, since there is a new issue about the videos.
It's not clear to me if @Woseseltops is going to modify the video models as well. (#1332)
I fixed some other bugs with the videos on my branch. But @Woseseltops has not looked at the code yet.

**Review by Woseseltops — APPROVED** [review]
Code looks okay to me (apart from a few cases of camelCase where we use under_score stuff in the rest the code)!

**Comment by susanodd** [comment]
@Jetske I'll look at this on Monday.
I deployed the fixes to the zip import #1331 #1340 . This issue #1341 the videos seem to have been uploaded.
But the file permissions are all over the place. So perhaps something else is going on.

**Comment by susanodd** [comment]
@Jetske we have that same inconsistency problem again. #1342 
That means that migrations cannot be applied right now.

**Pull request merged**
