### PR TITLE
#1356: Patch to prevent 7-char sequence and missing objects

### PR DESCRIPTION
**Pull request by susanodd**
Remove an existing gloss video file that does not have an object; lazy creation of gloss video object if file does not have it.

Solution thought up by @Jetske and @susanodd when looking at the video storage.

This patch includes two parts.

- if a Gloss Detail page is visited and there is a video file but there is no GlossVideo object pointing to it, an object is created for it.

- if a new video is being uploaded but there already exists a file with this name, but no GlossVideo object, the file is deleted so that the new file can have a correct path, without the 7-char code added to it.

Based on recent video creations, this is happening, so this is necessary.

If you want to try this out on your local signbank, then 

- set DEBUG_VIDEOS to True.
- Then for a particular gloss, remove its videos in Gloss Edit.
- Then on the file system, copy a video file to the "normal" location for this gloss's video file. (I.e., put back the video file, but on the file system, not using the Form upload.
- Then try either "renewing the page" (the new GlossVideo object will be created and you will see messages in the venv log.
- Or immediately upload a new video without reloading the page. Then the "add video" will erase the file before creating a new object. This prevents a weird file name from being created.

TO DO (different branch)
Part 3, if there already is a file with the weird filename, the object and the file both need to be fixed.
This has recently happened with NOORD-KOREA-B. It already had a video, but no GlossVideo object. So the new video has a 7-char sequence.

We don't know how it happens that a GlossVideo object is not created. Perhaps the transaction does not complete or there is a file system error, or the database is locked.

### CODE REVIEW

**Comment by vanlummelhuizen** [comment]
> Based on recent video creations, this is happening, so this is necessary.

Have you seen filenames with the 7-char sequence being created? It would be nice to know in what situation it happens.

I think it is good if we could also do this in batch mode, e.g. with a Django command. If we do this, and clean up other things (see also https://github.com/Signbank/Global-signbank/issues/910#issuecomment-2459751097) we avoid that the clean up is only done when Signbank is used.

**Comment by susanodd** [comment]
> > Based on recent video creations, this is happening, so this is necessary.
> 
> Have you seen filenames with the 7-char sequence being created? It would be nice to know in what situation it happens.
> 
> I think it is good if we could also do this in batch mode, e.g. with a Django command. If we do this, and clean up other things (see also [#910 (comment)](https://github.com/Signbank/Global-signbank/issues/910#issuecomment-2459751097)) we avoid that the clean up is only done when Signbank is used.

Yes, we investigated this. There was a recent one for NOORD-KOREA-B. So we looked at the files and at the admin.
There already existed a file for the gloss, but there was no GlossVideo object for that file. The file sizes were identical. The old file was from the past. The new file ended up with the 7-char sequence. And that was also inside its path in GlossVideo.
So it creates this sequence if there already exists a file with the desired name. (Django does this. It's that Django implementation  function in the issue.)

I suspect it's something to do with the database getting locked that it hasn't finished making the object and then ends up locked but saved the file but didn't complete.

**Comment by susanodd** [comment]
All the GlossVideo objects with non-existent file paths have been deleted.
I did this in the admin by hand. That way I could confirm every removal.

**Review by Woseseltops — CHANGES_REQUESTED** [review]
Thank you for providing bite sized pull requests :).

About the code:
* I think the changes in ``signbank/dictionary/models.py`` are a good opportunity for a guard clause :).
* I think the function name `get_video_path()` is a bit misleading if that functionality will also correct missing connections. If we don't want to rename the function to better reflect that logic inside, perhaps we can 'communicate' this extra behavior by making it optional, and including a parameter for it? Something like `get_video_path(fix_videos_without_glossvideo_object=True)`
* I think this is easier to maintain with f-strings:

```python
name = str(self.examplesentence.id) + ': ' + str(self.action) + ', (' + str(self.datestamp) + ')'
```

```python
name = f"{self.examplesentence.id}: {self.action}, ({self.datestamp})"
```

About the functionality: creative solution to 'fix' the connections when they are visited in the UI... but wouldn't it make more sense to have a management command that can check and fix all of Signbank? I see @vanlummelhuizen also suggests this. Perhaps good for a separate issue?

**Comment by susanodd** [comment]
> Thank you for providing bite sized pull requests :).
> 
> About the code:
> 
>     * I think the changes in `signbank/dictionary/models.py` are a good opportunity for a guard clause :).

Okay.

>     * I think the function name `get_video_path()` is a bit misleading if that functionality will also correct missing connections. If we don't want to rename the function to better reflect that logic inside, perhaps we can 'communicate' this extra behavior by making it optional, and including a parameter for it? Something like `get_video_path(fix_videos_without_glossvideo_object=True)`

I'll modify the name. The function is called a lot. It can't be easily called in the templates if there are parameters. (Yes, then to use a vertical bar as is done for other functions that required the language. (There are actually about 5 different functions that kind of overlap. It used to be an option on some functions to check whether the file exists. But if that's not checked, it causes other problems.)

I can't really see why we would want to "not" use it. When we switched to field choice objects, there were some functions that were changed in order to support the "change" since it was difficult to find all the places in the code. Then that code was evolved away after it was all working.

This is meant as a patch since we can't control the API transactions from not completing.

>     * I think this is easier to maintain with f-strings:
> 
> 
> ```python
> name = str(self.examplesentence.id) + ': ' + str(self.action) + ', (' + str(self.datestamp) + ')'
> ```
> 
> ```python
> name = f"{self.examplesentence.id}: {self.action}, ({self.datestamp})"
> ```

That's @Jetske's code. Yes, the f-strings are cool.

> About the functionality: creative solution to 'fix' the connections when they are visited in the UI... but wouldn't it make more sense to have a management command that can check and fix all of Signbank? I see @vanlummelhuizen also suggests this. Perhaps good for a separate issue?

Yes, I am making a management command. Except we don't actually know how these file names arise. (If a transaction does not complete because the database gets locked. That's what I suspect.)

**Comment by susanodd** [comment]
Another question, what do we think about non-mp4 videos?

**Review by Woseseltops — APPROVED** [review]

**Pull request merged**
