### PR TITLE
Command added for finding unused files and test #833

### PR DESCRIPTION
**Pull request by Jetske**

### CODE REVIEW

**Review by Woseseltops — COMMENTED** [review]
This seems like good code to me, thanks! :) 

General things I noticed:

* I see relatively short variable names, like `notexist` or `todelete`. Given that we all use autocomplete, I slightly prefer more description ones, like  `non_existant_file_names` or `files_to_delete`.
* Code that is split up into 'paragraphs', containing a few lines that are functionally coherent, is easier to review. So instead of:

```python
    self.stdout.write("\nUnused files found are:\n")
    for unknown_file in notexist:
        self.stdout.write(unknown_file)
    if len(notexist)>0:
        # Ask user to agree
        todelete = input("Delete files? [Y/N]")
        if todelete.lower() == "y":
            for subdir, dirs, files in os.walk(chosen_path):
                for file in files:
                    if file in notexist:
                        os.remove(os.path.join(subdir, file))
            self.stdout.write('Files are deleted')
        else: 
            self.stdout.write('Files are not deleted')
    else: 
        self.stdout.write('No unused files found')
```

you could do 

```python 
    self.stdout.write("\nUnused files found are:\n")

    for unknown_file in notexist:
        self.stdout.write(unknown_file)

    if len(notexist)>0:

        # Ask user to agree
        todelete = input("Delete files? [Y/N]")

        if todelete.lower() == "y":
            for subdir, dirs, files in os.walk(chosen_path):
                for file in files:
                    if file in notexist:
                        os.remove(os.path.join(subdir, file))
            self.stdout.write('Files are deleted')

        else: 
            self.stdout.write('Files are not deleted')

    else: 
        self.stdout.write('No unused files found')
```

* We try to work with guard clauses where we eliminate the error conditions first, and then have the happy path unindented. So instead of the above, you could do

```python 
    # First condition: no unused files
    if len(notexist) <= 0:
        self.stdout.write('No unused files found')
        return

     # Second conditins: ask user to agree
     if input("Delete files? [Y/N]").lower() != 'y':
            self.stdout.write('Files are not deleted')
            return

    for subdir, dirs, files in os.walk(chosen_path):
        for file in files:
            if file in notexist:
                os.remove(os.path.join(subdir, file))

    self.stdout.write('Files are deleted')
```

Two specific thoughts about:

```python
        if pathtype == "other_media":
            chosen_path = os.path.join(os.path.join(settings.WRITABLE_FOLDER),settings.OTHER_MEDIA_DIRECTORY)
            for other_media_file in OtherMedia.objects.all().iterator():
                filenames.append(other_media_file.path.split("/")[-1])
        elif pathtype == "video":
            chosen_path = os.path.join(os.path.join(settings.WRITABLE_FOLDER),settings.GLOSS_VIDEO_DIRECTORY)
            for gloss_video in GlossVideo.objects.all().iterator():
                filenames.append(gloss_video.videofile.name.split("/")[-1])     
        else: 
            self.stdout.write("Wrong argument: try 'video' or 'other_media'")
            return
```

* This function seems to consists of 3 steps (find file names, figure out which are unused, and delete them), but only the latter two have a separate function... why not all of them for consistency?

* This approach avoids some repetition, what do you think?

```python
if pathtype == 'other_media':
    directory = settings.OTHER_MEDIA_DIRECTORY
    objects = OtherMedia.objects
else pathtype == 'video':
    directory = settings.GLOSS_VIDEO_DIRECTORY
    objects = GlossVideo.objects

chosen_path = os.path.join(os.path.join(settings.WRITABLE_FOLDER),directory)
for gloss_video in objects.all().iterator():
    filenames.append(gloss_video.videofile.name.split("/")[-1])                    
```

**Comment by Jetske** [comment]
Great! I've changed most of the code according to your review. The only issue is with the last note to avoid repetition. I wanted to do that, but 'videofile' does not work for both video and other_media. For other_media you need to search for 'path' and for video to 'videofile.name'. But let me know if you know of another way.

**Comment by susanodd** [comment]
Here is a screenshot of GlossVideo in the Admin. You see some filenames with ".bak" or ".bak1234" at the end. Although these are in GlossVideo and are on the filesystem, they are not used anymore in display. They are also inaccessible to the user.

glossvideo-admin-filenames

It would be welcome if these can be tracked down and removed as well.

**Comment by vanlummelhuizen** [comment]
> Here is a screenshot of GlossVideo in the Admin. You see some filenames with ".bak" or ".bak1234" at the end. Although these are in GlossVideo and are on the filesystem, they are not used anymore in display. They are also inaccessible to the user.

@susanodd I believe these `.bak` files can become accessible again if the current video/other media file is deleted. So, they should not be removed from the DB and system.

**Comment by vanlummelhuizen** [comment]
About this pull request: I am happy. So we could merge this as far as I'm concerned.

**Review by vanlummelhuizen — APPROVED** [review]

**Comment by susanodd** [comment]
@vanlummelhuizen can you point out in the code where this is actually done?

**Comment by vanlummelhuizen** [comment]
@susanodd 
> can you point out in the code where this is actually done?

See 
https://github.com/Signbank/Global-signbank/blob/8c3ae490e4084ff8e7df2a6ae8f35b658787b832/signbank/video/views.py#L57-L60
and
https://github.com/Signbank/Global-signbank/blob/8c3ae490e4084ff8e7df2a6ae8f35b658787b832/signbank/video/models.py#L331-L373

**Comment by susanodd** [comment]
Okay, fine.

**Review by susanodd — APPROVED** [review]

**Pull request merged**
