### PR TITLE
New interface languages and language picker

### PR DESCRIPTION
**Pull request by Woseseltops**
In this pull request:
* #696 Added two new interface languages: Hebrew and Arabic 
* #696 Wired the language picker to the interface languages in the settings (no longer dynamic) 
* #696 Removed the flags and animations from the language picker
* #703 Unified tooltip html to single location, made it translatable

Points of doubt:
* I added this setting, which populates how the languages are called in the language picker:

``
#Short (abbreviated) version of how language users call their language, to be used in the language picker
INTERFACE_LANGUAGE_SHORT_NAMES = ['EN','NL','官话','עִברִית','عربى'] 
``

A prettier solution, I think, would be to add this to the language objects in the Django admin, as this is where we specify how languages are called in other languages anyway. However, because this would require an extra database migration, which is inconvenient as there are already migrations going on at at least one other branch, I've postponed it for now.
* Adding new interface languages also means that all models that have fields that are influenced by django-model-translation should get extended... I forgot how this worked again, and I guess this is also a database migration?

### CODE REVIEW

**Comment by vanlummelhuizen** [comment]
Thanks @Woseseltops. I have one issue: if you add languages to the LANGUAGES setting, a makemigrations would add those languages to translated model fields. I tried it out and got

```
    - Add field name_ar to language
    - Add field name_he to language
```

The main question here is: do we need to also translate language names to those new languages? If yes, we need to make migrations and use them. If not, we could add a MODELTRANSLATION_LANGUAGES setting that does not have the new languages. 

Making a migration at this point does not pose any problems if you merge from master first. That means you could also add another field to Language.

**Comment by Woseseltops** [comment]
Okay so the answer to my point...

> Adding new interface languages also means that all models that have fields that are influenced by django-model-translation should get extended... I forgot how this worked again, and I guess this is also a database migration?

... is to do a `makemigrations`, which indeed results in a migration and is thus something we should avoid.

> Making a migration at this point does not pose any problems if you merge from master first. That means you could also add another field to Language.

Do you mean you have no migration files in your separate branch, and I can just make migrations as long as I put them on the master branch as fast as possible? Because then maybe we could avoid what I am talking about below:

> The main question here is: do we need to also translate language names to those new languages? If yes, we need to make migrations and use them. If not, we could add a MODELTRANSLATION_LANGUAGES setting that does not have the new languages.

To make things more concrete, this about cases where you for example select Arabic as interface language, and then look at the NGT dataset which has Dutch as a translation language; Signbank will needs to know the Arabic translation of the name 'Dutch', and will try get this via field `name_ar`, which is automatically generated by django_model_translation. Without doing a migration, I expect errors like `No column name_ar for table Dictionary_language` or something like that. 

Are you suggesting we modify the template so that it only shows a translated language name if we say so in a setting, and if not show the name of the language in the 'main' interface language (which is English)?

**Comment by vanlummelhuizen** [comment]
Sorry for the late reply.

> Do you mean you have no migration files in your separate branch, and I can just make migrations as long as I put them on the master branch as fast as possible?

In branch [fieldchoice_field_translations_658_661](https://github.com/Signbank/Global-signbank/tree/fieldchoice_field_translations_658_661) I  do have migrations, but since I do not know when it is finished I believe I cannot block migrations on other branches. Furthermore, I now have some experience in resolving migration conflicts because I have merged two branches that both contained new migrations. As I said earlier somewhere, merging my branch with master is going to be hard, so having a few extra migrations to deal with is ok.

> Are you suggesting we modify the template so that it only shows a translated language name if we say so in a setting, and if not show the name of the language in the 'main' interface language (which is English)?

I am not sure this is a template thing, but I think this is the essence. We are talking about two language uses:

1. Interface language (.mo and .po files)
2. data language governed by django-modeltranslation (now only Language.name, later also FieldChoice.name)

Both of them are now based on the LANGUAGE setting. If we separate them, we need a fallback translation language (English), but we avoid making a migration.

**Comment by Woseseltops** [comment]
Outcome face to face conversation: MODELTRANSLATION_LANGUAGES is an existing option offered by django-modeltranslation which should stop `No column name_ar for table Dictionary_language` from happening. That means no migrations. 

To do:
* Add an extra commit to test the setting.
* Merge.

**Pull request merged**
