### PR TITLE
Show warning on delete sign in gloss edit view if references other glosses

### PR DESCRIPTION
**Pull request by susanodd**
Information has been added to the modal for Delete this sign.

At the moment, I commented out the actual gloss.delete() in update.py
Do we want to prevent the user from deleting the gloss if it's related to other objects?

### CODE REVIEW

**Comment by susanodd** [comment]
I'm still working on this one. Trying to condense the code now.

**Comment by susanodd** [comment]
This one is finished now. The delete is turned back on. If you try it on real data that has no related objects, it will actually delete the gloss. (I did this on my local database and deleted something I didn't want to delete. Then typed it all in from the one on Global. Really annoying. But it works.)

**Comment by susanodd** [comment]
You may want to try this out on your local server to see how it works.
Only the tstMH dataset has sufficient (nonsense) relations between glosses and morphology filled in to test it.

**Comment by susanodd** [comment]
This may need to be synced with #659.
(Although totally different issue. I'm afraid to delete signs, so I haven't investigated what happens when they actually are deleted.
This merge request merely does what issue #127 wishes.

**Comment by susanodd** [comment]
Now that we have the query parameters implemented, it would be possible to store the phonology in the DeletedGlossOrMedia info. (It's really annoying if you delete a gloss you didn't mean to.)

**Comment by susanodd** [comment]
I added screenshots to the issue #127.

**Comment by susanodd** [comment]
I added an Admin class for DeletedGlossOrMediaAdmin so it's possible to browse them in the admin.
(No add or delete permissions.)

**Comment by vanlummelhuizen** [comment]
> At the moment, I commented out the actual gloss.delete() in update.py
> Do we want to prevent the user from deleting the gloss if it's related to other objects?

#127 only talks about warning before deleting, not preventing deletion. So, I think you should uncomment the  `gloss.delete()` line.

**Comment by susanodd** [comment]
> > At the moment, I commented out the actual gloss.delete() in update.py
> > Do we want to prevent the user from deleting the gloss if it's related to other objects?
> 
> #127 only talks about warning before deleting, not preventing deletion. So, I think you should uncomment the `gloss.delete()` line.

It's possible to delete now.
There is an if that checks though.

Do we need to physically remove the things it's related to? (For relations I think this is the case because other code explicitly removes things.)

(I don't know.)

**Comment by vanlummelhuizen** [comment]
My rule of thumb: If something is removed, the relations it had are also removed. But the things it was related to, are NOT removed.

**Comment by susanodd** [comment]
Okay. I'll put the button back, but as a danger button.
And I'll add a settings GUARDED_GLOSS_DELETE set to False as default.

**Comment by susanodd** [comment]
This one is ready. I revised the layout and text of the delete modal. Screenshots in the issue.

**Pull request merged**
