### PR TITLE
Textual changes and translations edited #879

### PR DESCRIPTION
**Pull request by Jetske**

### CODE REVIEW

**Comment by susanodd** [comment]
In order to allow translation of the fuzzy strings, you need to remove the `#, fuzzy` line and `#| msgid <string>` above the (fixed) translation.

There is a problem here:

https://github.com/Signbank/Global-signbank/blob/e9071d857d6f74dc9a63d3cbd623a1faa3a53f36/conf/locale/nl/LC_MESSAGES/django.po#L2513-L2523

Above, Django is being instructed to translate Query View to Frequencies. (Because it didn't find anything appropriate, it is basing its translation on the fuzzy part.)

If we just want to get rid of View everywhere, then the first could be `Query Lijst` and the second `Query`.

**Comment by Jetske** [comment]
Thanks Susan, I didn't know about the fuzzy part. 

I think for Query View that 'view' is okay to stay (for now). What is the reason that it was translated before to 'Frequentie-weergave' instead of just 'Query-weergave'?

**Comment by susanodd** [comment]
Django does that automatically. The fuzzy ones are ones it can't find any matches for, then it tries to guess. That's why on those fuzzy ones you always need to check what the thing it's using right below the line fuzzy, that it's the correct thing.
Sometimes it's hilarious what it's attempting to translate. (!)

**Comment by Woseseltops** [comment]
I guess the suggestions by @susanodd still need to be processed before this can be merged, right?

**Comment by Jetske** [comment]
@Woseseltops no, I believe they were processed in the 2nd commit

**Comment by susanodd** [comment]
Approved.

**Pull request merged**
