### PR TITLE
Issue #755: Fixed Registration.

### PR DESCRIPTION
**Pull request by susanodd**
This branch fixes the registration of new users.

Some legacy code has been removed.

### CODE REVIEW

**Review by Woseseltops — APPROVED** [review]
Hey @susanodd , great to see this fixed! Going over the code, I get the feeling that this was mostly a matter of changing how the various pages that are part of the process link/forward to each other. If that was the solution, how do you think it's possible that this worked before?

**Comment by susanodd** [comment]
I removed some lines from the end of the __init__ that called the superclass. (of the RegistrationForm)
https://github.com/Signbank/Global-signbank/blob/a81d60a3bdee0c6920ee305b9c54847714b1598a/signbank/registration/forms.py#L151
There was code after that that I removed.
and I added a **data=**request.POST to the creation of the form. It didn't have the "data=".

Maybe there was an upgrade to something? 

https://github.com/Signbank/Global-signbank/blob/a81d60a3bdee0c6920ee305b9c54847714b1598a/signbank/registration/views.py#L195

I deleted a bunch of legacy code, with extra parameters here and there.
I don't actually know. It could have been broken for a long time. @ocrasborn didn't recall when it was last working.

**Comment by Woseseltops** [comment]
Sorry I didn't manage to look into this today, got this planned for next Thursday!

**Comment by Woseseltops** [comment]
Hmm weird, anything... let's merge and have it fixed again!

**Pull request merged**
