### PR TITLE
Move button to switch dataset of gloss

### PR DESCRIPTION
**Pull request by susanodd**
A button has been added to GlossDetailView to allow moving a gloss to a different dataset. #1119 

This involved updating the lemma field dataset to the new dataset.
To maintain consistency, the dataset of the related glosses (via relations or morphology) are also changed.
To do the morphology, reverse morphology is also retrieved in related objects.
For example, gloss Ijsbeer = Ijs + beer.
If any of these glosses is moved, the others also need to be moved.
This is done in an atomic transaction.

The videos and images of the gloss(es) are also moved to the new dataset.
This is done using a signal. (As for other updates.)

At the moment, there are checks that the user is a superuser in order to do this.
Both datasets must be selected.

The existence of the gloss already in the target dataset is checked.

- An error feedback is shown

If the gloss can't be moved because of a similar gloss in the target dataset:
- Expect the user to change the lemma translations and gloss annotations to remove ambiguity.
- The target dataset must have the same translation languages

Relations can be transitive. Once some glosses that are related are moved, this will also need to move more glosses.

- Assumes that the user will look before jumping.

That the annotation and lemma texts non-overlap are soft constraints on the dataset (This is checked manually by all the code.) The use of one text per language is a Django constraint.

```
      AnnotationIdglossTranslation
                 unique_together = (("gloss", "language"),)

      LemmaIdglossTranslation
                unique_together = (("lemma", "language"),)  # For each combination of lemma and language there is just one text.
```

### CODE REVIEW

**Comment by Jetske** [comment]
If the gloss and/or its related glosses do happen to already exist, are they overwritten? I think this should either not be allowed, or show a warning with exactly which glosses will be replaced. 

Would it be safer to copy them rather than moving?

**Comment by susanodd** [comment]
I revised to code to give feedback instead of moving the gloss if the translation languages of the target dataset are different, or if the lemma or annotation texts already exist in the dataset.

I did not do checks on the related glosses. They are visible in the modal so the user can see what the related glosses are.

The issue is for use to move the Oefen glosses to NGT. So I am assuming that we will be doing this.
I checked by hand to see how many glosses have related glosses. At the moment, it's in the morphology.

I doubt anything bad will happen. I tried it out on SIBILING-C to see if the warnings work okay for trying to move it to NGT.

I'll see what I can do about the related glosses. (Basically, the only "solution" would be to add -A -B -C to the glosses in order to move them. So not do anything if there will be ambiguity.)

**Comment by susanodd** [comment]
I'll try out what happens if the morphology related glosses are already in the target dataset.
I guess it could give feedback on those glosses and not do anything.

The other media is automatically in the right place because it's stored under a folder gloss id. It doesn't need to be moved.

**Comment by susanodd** [comment]
It's going to be at least Thursday before the code can be used on Global.
I didn't get the ansible scripts working all the way. So the master can't be deployed on signbank yet.

**Comment by susanodd** [comment]
I guess I'll add the bullet explainations above to the modal.

**Comment by susanodd** [comment]
@Jetske I modified the description of the command in the model. (See screenshots #1119)

There are also screenshots of the relations view in the target dataset with the images moved.

**Pull request merged**
