### PR TITLE
Semantic fields are multiple choice

### PR DESCRIPTION
**Pull request by susanodd**
This branch makes semantic fields multiple choice.
This is the first part of #762 .

New classes have been created to support this: SemanticField and SemanticFieldTranslation.
Only English is stored in SemanticField under the field "name".
Other translations can be created for other languages in SemanticFieldTranslation.
There is a url for showing all the semantic fields:
/dictionary/semanticfields/
Here the user can also see the translations.
Details are shown in a semantic field detail view. (Analogous to Handshapes.)

In the Gloss model, a new field has been added, semFieldShadow, which is a ManyToManyField with SemanticField.
(This is analogous to another multiple select field Dialect.)
Because semField is a FieldChoice, the functionality for semField in choice lists has been maintained.
The field choices for semField are used in the pull-down menus for Gloss Search.

The Admin supports the two new classes.
Bookkeeping is done to make sure when new semantic fields are created, they are present in both formalisms.
(This is how Handshapes are maintained, in their own class as well as in FieldChoice.)
Furthermore, testing has been added to check that searching on a semantic field, or on two semantic fields, results in a gloss being found.

This branch has a database migration.

Update 30.03.22

Derivation History is now also multiselect.
It has been implemented analogously to Semantic Field, with all the frazzle dazzle.
It also has a database migration.

### CODE REVIEW

**Review by Woseseltops — CHANGES_REQUESTED** [review]
Overall: high quality code, as far a I can see. I have one larger thing and one smaller thing.

Larger thing: `configure_derivationhistory` creates HTML by manipulating strings. I think the Django template language was intended to avoid this... would it be possible to do the same thing with Django templates? If so, I think that would the preferred approach.

Smaller thing: `update_semanticfield` and `update_derivationhistory` contain an `except` without Exception

**Comment by susanodd** [comment]
Eeeks! I see what you mean, that except statement is way overloaded.

**Comment by susanodd** [comment]
The configure url is basically a patch. It should only be used once. And only needed by Global.
Although it looks like a patch. It only exists because the DerivationHistory and FieldChoice shouldn't be empty.
For the Handshapes and SemanticFields, there was already data in FieldChoice.
But now FieldChoice has no data for derivHist (except for ASL).
Is it desirable to make the configuration elegant?
I've kind of done it a brute force hack job kind of implementation. :|
At the very least it could stay empty I guess and just let the user see there are no choices?
Or I could make it elegant and let the Admin enter values during configure.
(With a proposed suggestion of those used now, with "Use these?")

**Comment by susanodd** [comment]
Finished @Woseseltops !

**Pull request merged**
