### PR TITLE
Issue #648: Extend Expiry facility added to User Profile.

### PR DESCRIPTION
**Pull request by susanodd**
This branch adds a button to user profile to extend the expiry date of their account.
The button is shown when there are less than 60 days remaining.
Pushing the button results in extending the expiry by 6 months.
This is done without need for the Admin.

### CODE REVIEW

**Comment by Woseseltops** [comment]
Can I suggest working with guard clauses here again, to make the happy path clearer? So instead of

```python
def update_expiry(request):
    # if something is wrong with the call, proceed to Signbank Welcome Page
    # This can happen if the user types in the url rather than getting there via the User Profile View
    # And the Extend Expiry button was not shown on their profile
    if request.method != "POST":
        return HttpResponseRedirect(settings.URL + settings.PREFIX_URL + '/')

    if 'username' in request.POST.keys():
        username = request.POST['username']
    else:
        username = ''

    if username and request.user.username == username:
        try:
            user_profile = UserProfile.objects.get(user=request.user)
        except ObjectDoesNotExist:
            HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        from dateutil.relativedelta import relativedelta
        expiry = getattr(user_profile, 'expiry_date')
        if expiry:
            user_profile.expiry_date = expiry + relativedelta(months=+6)
            user_profile.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
```

Something like this

```python
def update_expiry(request):

    # if something is wrong with the call, proceed to Signbank Welcome Page
    # This can happen if the user types in the url rather than getting there via the User Profile View
    # And the Extend Expiry button was not shown on their profile

    #Check for request type
    if request.method != "POST":
        return HttpResponseRedirect(settings.URL + settings.PREFIX_URL + '/')

    #Check if we have a username
    if 'username' in request.POST.keys():
        username = request.POST['username']
    else:
        username = ''

    if not username or request.user.username != username:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    #Check if user exists
    try:
        user_profile = UserProfile.objects.get(user=request.user)
    except ObjectDoesNotExist:
        HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    from dateutil.relativedelta import relativedelta
    expiry = getattr(user_profile, 'expiry_date')

    #Check if we have an expiry date
    if not expiry:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    #Update the exprity date
    user_profile.expiry_date = expiry + relativedelta(months=+6)
    user_profile.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

```

**Comment by susanodd** [comment]
Yes, I see that is much easier to read!

**Comment by susanodd** [comment]
This has been done as suggested!

Now just awaiting approval from @ocrasborn.

**Comment by susanodd** [comment]
This has been approved off-line by @ocrasborn.
I'm merging it into master.

**Pull request merged**
